### ISSUE TITLE
Resart VS Without Loading Extensions

### ISSUE THREAD

**Issue by RealDotNetDave** [madskristensen/Tweakster#1]
Can you add to this extension the ability to restart Visual Studio without loading any extensions or add-ins? The biggest reason is to help track down issues with extensions. Also, as a speaker at conferences, I could really use this for demos.

**Comment by madskristensen** [comment]
_Restart in SafeMode_ is now implemented. Please help testing it out by installing the latest [CI build](https://www.vsixgallery.com/extension/0c8bd9fa-77d5-4563-ab57-9e01608c3d04).

![image](https://user-images.githubusercontent.com/1258877/88462228-b52b8f80-ce5e-11ea-9e89-ba9adc6b29a0.png)
