### ISSUE TITLE
Side-tab interferes with `Alt` key

### ISSUE THREAD

**Issue by hakenr** [madskristensen/Tweakster#100]
On my computer, in ~50% of cases, when I hold the `Alt` key (e.g for Alt-Tab, or any other combination) the side-view activates:

![2022-04-11_09-36-09](https://user-images.githubusercontent.com/12828888/162687669-498fe28b-5935-493d-af06-fb0cd4447145.gif)

https://www.screencast.com/t/dh27mkHjnx

When I disable Tweaks 2022 (v1.1.132) the issue disappears.

**Comment by hakenr** [comment]
Might be same issue as #99.

**Comment by hakenr** [comment]
Probably needs 1 sec or more of the `Alt` key to be pressed.

**Comment by Velociraptor45** [comment]
I can confirm that issue. Took me an annoyingly long time to find out what was actually causing it.

**Comment by jhigh2000** [comment]
I think I'm still hitting this bug through a different vector even after this fix - occasionally the Peek Definition (ALT-F12) triggers the open to the side feature and the active document splits off to a new docked window.
