### ISSUE TITLE
Bin  & obj folder not being removed on clean command

### ISSUE THREAD

**Issue by bimal-b** [madskristensen/Tweakster#12]
When I clean my projects, bin and obj folders are not being removed. 
Following is the config:
OS: Win 10 Build 20180
VS 2019 Enterprise
Sample Project : https://github.com/bimal-b/Binger

**Comment by madskristensen** [comment]
The bin and obj folders are removed before the regular *Clean* command runs. For many project types, *Clean* will add empty bin and obj folders back. Here's a description of the feature from Tweaks readme file:

> Both *bin* and *obj* are now fully deleted when the *Clean* command is executed. It does so right before the regular *Clean* command runs. The *Clean* command will add the *bin* and *obj* folders back, so be aware of that when testing this feature. 

In other words, this is by design

**Comment by bimal-b** [comment]
Thanks. I tested again. it is working as you described.
Closing the issue.
