### ISSUE TITLE
Ctrl + W does not close tab

### ISSUE THREAD

**Issue by AlexVPerl** [madskristensen/Tweakster#13]
Thank you for creating this extension. Ctrl + W does not close tab on VS 2019, it just selects current line, current paragraph, etc. Is there any additional settings required to make Ctrl + W work?

**Comment by madskristensen** [comment]
It would work fine, but it won't kick in until the extension is fully loaded and, due to the async extension loading nature of VS, could happen several 30 seconds after your solution has loaded.

**Comment by jenscski** [comment]
Same problem here, Ctrl + W does not close tab.

Looks like VS i waiting for next keystroke. (double Ctrl+W opens internal browser pointing at https://visualstudio.microsoft.com/)

![image](https://user-images.githubusercontent.com/4134254/89269914-e2382900-d63a-11ea-876b-ed50b0421ee5.png)

**Comment by AlexVPerl** [comment]
I waited for my solution to fully load, even hours later Ctrl + W still just selects current line/paragraph/etc. I even went into VS settings for shortcuts and removed anything mapped to Ctrl + W but still nothing. Would love to have it working. BTW I do not see the same message as @jenscski for some reason.

**Comment by madskristensen** [comment]
I'm beginning to think that it varies by what workloads people have installed in their VS instance. I think I need a different way to hook into the keybinding system to do this

**Comment by AlexVPerl** [comment]
Yeah that's probably it. 

I got it working by just remapping Window.CloseDocumentWindow shortcut: https://gist.github.com/jpoehls/2030795

Issue was that Ctrl + W was mapped to a whole bunch of other actions (3 others, VS does not check for conflicts it seems). I think in your extension you'd just have to check if other things are mapped to it and clear those shortcuts.

**Comment by madskristensen** [comment]
I've completely changed implementation, so it bypasses the VS keybinding system and binds directly to the `MainWindow`'s keyboard events. Please try the latest [CI build](https://www.vsixgallery.com/extension/0c8bd9fa-77d5-4563-ab57-9e01608c3d04) and verify if this now works for you.

**Comment by jenscski** [comment]
Looks like that fixed it, I installed version 1.0.74, and now it works on my setup.

Thanks

**Comment by madskristensen** [comment]
@AlexVPerl can you verify as well, please. Then the issue can be closed.

**Comment by luebster** [comment]
I already had Ctrl + W bound to File.Close command. When I pressed Ctrl + W, Visual Studio was closing two tabs! Took me a few minutes to figure out what was actually happening. Perhaps add a note to your documentation to verify this keystroke is not already bound. Or perhaps you can clear it when the extension installs and/or loads?

**Comment by madskristensen** [comment]
Closing this ticket since the double closing is captured by #22
