### ISSUE TITLE
Open project from Jump-List as Administrator

### ISSUE THREAD

**Issue by mrlacey** [madskristensen/Tweakster#15]
I have my VS set up to always run as Administrator.
However, when I open a project/solution from the taskbar jump-list it doesn't launch as administrator.

Is this something that could be _tweaked_?

**Comment by madskristensen** [comment]
I don't think it can be done from an extension, but have you looked at this: https://ppolyzos.com/2017/08/08/always-run-visual-studio-as-administrator/

**Comment by mrlacey** [comment]
> I don't think it can be done from an extension, but have you looked at this: https://ppolyzos.com/2017/08/08/always-run-visual-studio-as-administrator/

That's how I run as an administrator.

I didn't think there was a way of doing this as an extension but you're good at doing things I didn't know were possible. 😉 

I'll open a request on the developer community site.
