### ISSUE TITLE
Uninstall Tweakster, jumplist stick

### ISSUE THREAD

**Issue by jsassner** [madskristensen/Tweakster#17]
So i had some issue with my VS, and to search for the error i uninstalled all extensions (was unrelated thing).
I then noticed that the jumplist feature for tasks presentation mode and safe mode stuck there, and i wanted to show recent files instead. Alot of googling later i found out that i had to delete a file in  %AppData%\Roaming\Microsoft\Windows\Recent\CustomDestinations\ that contained visual studio presentation mode and safe mode - now i got my recent files list back again.

This is not a bug per se, but i wrote this if someone else have the same issue.

Perhaps i should add i don't use the standard windows start menu, i use Open-Shell if that matters.

**Comment by okmotsan** [comment]
I have the same problem, I installed the Tweaks 2022 extension, then found the "don't copy line" feature wasn't working and uninstalled, but it left the Presentation Mode and Safe Mode under Tasks when I right-click on the task bar for VS2022.
However I don't have the folder %AppData%\Roaming\Microsoft\Windows\Recent,  the closest thing is "Recent Items" under that Windows folder but that doesn't contain a CustomDestinations folder.  I searched the C: drive and didn't find "CustomDestinations" anywhere so I'm not sure how to manually remove those two tasks for Presentation/Safe mode.  Any ideas?
