### ISSUE TITLE
Recent Items is gone form Jump List

### ISSUE THREAD

**Issue by tbasallo** [madskristensen/Tweakster#18]
Adding custom items to the jump list seems to have removed the recent items jump list feature.

Can this be a setting OR have both?

**Comment by madskristensen** [comment]
I didn't see that happening for me. Weird. You on an updated version of Windows 10?

**Comment by jsassner** [comment]
See #17  also

**Comment by tbasallo** [comment]
Hmm.. Works as expected on 2004, "broken" on 1809.

**Comment by madskristensen** [comment]
@tbasallo hmmm is right :) Not sure why that is. And I'm on 1909 where it works fine too

**Comment by ben-page** [comment]
Broken on 1909, too. I disabled the extension and deleted CustomDestinations file, then the jump list went back to normal. After re-enabling the extension, I just have my pinned projects and the presentation mode options, no recents.
