### ISSUE TITLE
Ability to use different shortcut key to reset the zoom level

### ISSUE THREAD

**Issue by RobSiklos** [madskristensen/Tweakster#21]
It's great that you have CTRL+0 to reset the zoom level. However, this gets in the way of MANY compound shortcuts for TFS (Azure DevOps) which all begin with that. For example, CTRL+0,P to view pending changes.

I would like to request the ability to use a different shortcut key to reset the zoom, via configuration.

Alternatively, give me a way to disable the CTRL+0 shortcut entirely.

**Comment by madskristensen** [comment]
I'll release 1.0.76 in a few minutes. In that version you can go to **Tools -> Options -> Environment -> Keyboard** and change the shortcut for **View.ZoomReset**
