### ISSUE TITLE
Feature Suggestion: Reopen many closed files

### ISSUE THREAD

**Issue by ChayimFriedman2** [madskristensen/Tweakster#23]
Reopen closed file is great, but I used to reopen again and again more and more tabs in Chrome or VSCode. That is, it will be nice if  pressing Ctrl+Shift+T, Ctrl+Shift+T twice would open the two recently closed documents.

**Comment by madskristensen** [comment]
All feature requests to this extension must be backed by a real Visual Studio suggestion registered at [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=8). Please create one and post the link back here.
