### ISSUE TITLE
ALT GR + W closes the active document

### ISSUE THREAD

**Issue by ceifa** [madskristensen/Tweakster#24]
When I use alt gr + w, the current active document is closed, which is not the behavior of common applications(such as google chrome, etc).
I use alt gr + w to create the "?" char.

**Comment by madskristensen** [comment]
Any idea how to check for **AltGr**? [This line](https://github.com/madskristensen/Tweakster/blob/master/src/Tweaks/Editor/CloseActiveDocument.cs#L30) is supposed to only look for the **Ctrl** key

**Comment by ceifa** [comment]
@madskristensen **AltGr** is like "Ctrl + Alt" for the `System.Windows.Input` api. Fixed it doing a strict check instead of a flag check. Please check the PR.
