### ISSUE TITLE
CTRL + W select / expand selection

### ISSUE THREAD

**Issue by AlbertoMonteiro** [madskristensen/Tweakster#33]
One of my favorites features on ReSharper is the ability to press <kbd>CTRL</kbd> + <kbd>W</kbd> on the string opening/ending quotes and it does select the entire string, and if I keep pressing the <kbd>CTRL</kbd> + <kbd>W</kbd> it will expaned the selection over and over, and if I do <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>W</kbd>, it does the reverse.
It does not work only on string, if I am at the beginning of the method, if I do the shortcut it will select the entire method, including signature.
Here's an example of this working on Android Studio
![2020-08-30-22-17-38](https://user-images.githubusercontent.com/836496/91674479-3ede1500-eb0f-11ea-9e67-2206b99a44cf.gif)

**Comment by madskristensen** [comment]
Ctrl+W is mapped to closing of the document, which is an old ask from the community. In at least C# you can do it when by clicking `Shift+Alt+=` and `Shift+Alt+-` to go back

**Comment by AlbertoMonteiro** [comment]
Thanks, I didn't know about this existent shortcut that maps to `Edit.ExpandSelection` command

![image](https://user-images.githubusercontent.com/836496/92011082-f138f680-ed20-11ea-80d6-85d3e334698e.png)
