### ISSUE TITLE
Copy without indentation adds a carriage return to end of contents

### ISSUE THREAD

**Issue by StevenRasmussen** [madskristensen/Tweakster#35]
That was a great episode BTW!  So cool to see you code this enhancement live and in an hour!  I downloaded the extension and enabled the `Copy without indentation` feature which seems to be working great except that it adds a carriage return to the end of the contents.  So if you're doing a simple copy and paste of say a single word, it always adds a line break that you have to end up deleting.
![CopyWithoutIndentationIssue](https://user-images.githubusercontent.com/11198735/91735430-88f3e480-eb69-11ea-9610-dcd2fdd1e08d.gif)

**Comment by madskristensen** [comment]
That should be fixed in the latest version. Do you mind checking in latest [CI build](https://www.vsixgallery.com/extension/0c8bd9fa-77d5-4563-ab57-9e01608c3d04)?

**Comment by StevenRasmussen** [comment]
That did it! Thanks!
