### ISSUE TITLE
Shortcut for Reopen Document work (CTRL+SHIFT+T) is already used by Go To Files

### ISSUE THREAD

**Issue by yannduran** [madskristensen/Tweakster#37]
For me the current key chord `CTRL+SHIFT+T, CTRL+SHIFT+T` for the _Reopen Document_ command doesn't work because as soon as the first `CTRL+SHIFT+T` is pressed, the _Go To_ dialog opens set to _Go To Files_:

![image](https://user-images.githubusercontent.com/2031126/92316872-16897580-f03d-11ea-98f9-dff657266657.png)

`CTRL+T, CTRL+T` is available as is `CTRL+R, CTRL+D` which is actually more intuitive for **R**eopen **D**ocument.

**I'm happy to create a pull request that changes the shortcut to either of the suggested chords (or something else) if you also find that the current shortcut doesn't work, if you'd like me to go ahead and do that.**

**Comment by bilalmehrban** [comment]
I was just going to open the same issue. what I think is that there should be an option to modify the shortcuts of this extension.

**Comment by yannduran** [comment]
@bilalmehrban unfortunately extensions can't provide their own option for a user-selectable shortcut, but Visual Studio provides the UI to do so manually. 

Click on `Tools | Options | Environment | Keyboard`, search for _File.ReOpenClosedFile_, remove the `CTRL+SHIFT+T` shortcut currently added by the extension, and assign whatever shortcut you prefer.

Actually I don't know why `CTRL+SHIFT+Z` (_Edit.UndoClose_) doesn't seem to reopen a document/tab that's been closed. So I wonder why there's both _Edit.UndoClose_ and _File.ReopenDocument_ and what the difference between them  is supposed to be. 

@madskristensen do you know?

An already built-in way is `CTRL+T`, `R` and then select the file you want to reopen. You can select the file you want using the keyboard (using Up or Down arrow) and pressing `ENTER`, or clicking on a file in the list. 

Also `ALT+F`, `F` (or `ALT+F`, `ALT+F` - just don't let go of the `ALT` key in between) is a quick way to jump to _recent files list_ in the _File_ menu.

So maybe this _Tweaks_ command isn't even necessary? Or I guess it's a faster way of reopening the **last** closed document, as the built-in ways require selecting from a list. I think I might be using `CTRL+T`, `R` now that I've discovered it.

**Comment by bilalmehrban** [comment]
Thank you for the clarification 😊🤞
