### ISSUE TITLE
Copy/Paste Doesn't work for CSHTML Files

### ISSUE THREAD

**Issue by CTGreg** [madskristensen/Tweakster#43]
0. Create or open an existing C# Asp.Net MVC project
1. Open a CSHTML view
2. Copy a bit of code from the view
3. Paste it anywhere
4. Get unexpected result like this:
![image](https://user-images.githubusercontent.com/37312764/94034398-9a569800-fd87-11ea-96f1-f77e1f6691c4.png)

**Comment by CTGreg** [comment]
Here is the version
![image](https://user-images.githubusercontent.com/37312764/94034923-27015600-fd88-11ea-96c9-059fd86e4d9f.png)

**Comment by stefanloerwald** [comment]
I'm experiencing this issue too with .razor files.

**Comment by Dragonsangel** [comment]
This issue is also appearing in aspx and asmx files for me.
From what I have been able to figure out from what is copied, it seems that is copying the generated backend code.
Example:
The top part of my aspx site contains there lines:
```
<%@ Page Language="VB" %>
<%@ Import Namespace = "System"%>
<%@ Import Namespace = "System.ComponentModel"%>
<%@ Import Namespace = "System.Diagnostics"%>
<%@ Import Namespace = "System.Web.Services"%>
<%@ Import Namespace = "System.Web.Services.Protocols"%>
<%@ Import Namespace = "System.Xml.Serialization"%>
```

When I copy text that is further down, the text that is copied looks like this:
```
Imports System
Imports System.ComponentModel
```

**Comment by duncansmart** [comment]
Per https://developercommunity.visualstudio.com/content/problem/1193868/copy-and-paste-is-broken-in-razor-cshtml-files.html a workaround is to turn off the "Copy without indentation" feature in Tools > Options > Environment > Tweaks

**Comment by gpshonik** [comment]
Ended up here via https://developercommunity.visualstudio.com/content/problem/1201185/visual-studio-2019-v1674-copy-paste-not-working-co.html

**Comment by madskristensen** [comment]
This is now fixed in the latest version
