### ISSUE TITLE
Disabling Copy-Empty-Line and Copy-Empty-Selection no longer works

### ISSUE THREAD

**Issue by SpooRancher** [madskristensen/Tweakster#46]
When I first installed tweaks at about 16.7, these worked. Then they stopped (16.7.2??) and even though I have the options set to False, I get the horrible unmodified behaviour.

![image](https://user-images.githubusercontent.com/36959482/94734064-91a22b00-0360-11eb-8517-723821f0d724.png)

**Comment by fiseni** [comment]
On the other hand, with version 1.1.95 published on store on 10/8/2020, if you set "Copy empty lines" to true (the default behavior of VS), then copying the empty line no longer works. 
You can not duplicate the line with ctrl c, ctrl v.

**Comment by bert2** [comment]
@fiseni, this is caused by the feature "Copy without indentation". If you disable it in the settings then "Copy empty lines" and "Copy empty selection" should work again.

**Comment by fiseni** [comment]
Thanks for the hint @bert2
