### ISSUE TITLE
Copy without indentation copies/pastes the whole line

### ISSUE THREAD

**Issue by StevenRasmussen** [madskristensen/Tweakster#50]
Thanks for fixing #42.  It appears that the fix introduced a bug.  When selecting some text on a single line, it now pastes from the start of the selection until the end of that line:

![CopyIssue](https://user-images.githubusercontent.com/11198735/95495279-6f11a280-095c-11eb-9229-d2fa4da80d0d.gif)

**Comment by travbeamo** [comment]
I am also having same problem with Tweaks extension version 1.1.95 installed.

**Comment by dizarter** [comment]
Same problem. With option "Copy Without Identation" set to False, problem goes away.

**Comment by StevenRasmussen** [comment]
I can confirm the issue appears to be resolved now.  Thanks @madskristensen for the quick response on this!

**Comment by GrahamTheCoder** [comment]
I can also confirm 1.1.101 fixed this for me.

**Comment by tb-mtg** [comment]
Thanks @madskristensen
