### ISSUE TITLE
Feature Suggestion: Suggestion Mode for Intellisense by Default

### ISSUE THREAD

**Issue by mdro** [madskristensen/Tweakster#64]
Visual Studio currently always starts with Intellisense in completion mode: 
If a completion popup is open and you finish typing (by whitespace or punctuation) a word that is not in the completion list, it will automatically complete/change to the best match from the completion list.

The alternative is suggestion mode, where the unrecognised word will remain, while completions are only applied by tab and optionally return.
The reasons for using suggestions mode could be:
- The classic problem with autocorrect: When you mistype an identifier and it might get corrected to a different one. That wrong identifier is much harder to notice than a syntax error from non-existent identifier.
- When you write code top-down you might want to write a statement with an identifier that doesn't exist yet.

The suggestion is an option to activate suggestion mode on startup. I assume this is possible to implement in an extension?

Developer Community suggestion: [https://developercommunity.visualstudio.com/idea/838256/allow-toggling-between-suggestion-mode-or-completi.html](https://developercommunity.visualstudio.com/idea/838256/allow-toggling-between-suggestion-mode-or-completi.html)

**Comment by mdro** [comment]
Since this will be in-box in 16.10 I guess this should be closed? Or do you plan to add it before the 16.10 release or for people who can't upgrade (yet)?

Preview release notes: [https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.10.0.pre.1.0](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.10.0.pre.1.0)

**Comment by madskristensen** [comment]
Good point. I'll close it
