### ISSUE TITLE
Unexpectedly copying multiple lines

### ISSUE THREAD

**Issue by markheath** [madskristensen/Tweakster#67]
I've been trying to get to the bottom of a strange copying issue in VS and turns out it is the **Copy Without Indentation** feature. When I perform the following actions it copies two lines, when I would expect it only to copy one

1. Place cursor at the start of a line of code
2. Hold down shift and press down arrow (so one line of code is selected plus blank space on the line below)
3. Copy with Ctrl+C
4. Paste it somewhere - two lines have been copied

![VS2019copy3](https://user-images.githubusercontent.com/147668/102217540-9f356e80-3ed4-11eb-9e95-14c57c090652.gif)

I presume this is a bug? It's certainly not intuitive to me

**Comment by madskristensen** [comment]
This is fixed in the latest version (currently uploading to Marketplace)
