### ISSUE TITLE
Feature suggestion: Subword navigation aka Camel Humps in Editor

### ISSUE THREAD

**Issue by knoxi** [madskristensen/Tweakster#72]
This is a feature that a lot of IDEs have.

Basically have an option that changes the behavior of CTRL+RIGHT and CTRL+LEFT so that the caret stops at case change aka "Camel Humps".

**Comment by phizch** [comment]
This is quite an old issue, so you might have found it elsewhere, but that feature exist in Visual Studio 2022 at least.
CTRL+ALT+RIGHT and CTRL+ALT+LEFT moves to next/previous subword.

**Comment by knoxi** [comment]
You are right, and I'm already using it.
