### ISSUE TITLE
Copy/Paste copies more than the selection

### ISSUE THREAD

**Issue by Nils-Berghs** [madskristensen/Tweakster#81]
With the settings 

![image](https://user-images.githubusercontent.com/23696465/122011358-47f95380-cdbc-11eb-8190-fe10417678ad.png)

Selcting & Copying text from multiple lines will sometimes copy everything on those lines, not only the selected text:

Selection starting at the beginning of a line, ending in the middle of another line.
![image](https://user-images.githubusercontent.com/23696465/122014073-18981600-cdbf-11eb-9a0b-2560776474b2.png)
Copy/Paste result
  _"Applicaton": "Visual studio",
  "Description": "That f****** that can't get copy paste right",
  "UseName": "somename",
  "Password":_

Selection not at the beginning of a line, ending in the middle of another line.
![image](https://user-images.githubusercontent.com/23696465/122014479-7a588000-cdbf-11eb-9c80-99b4f581be7a.png)
Copy/Paste result
  _"Applicaton": "Visual studio",
  "Description": "That f****** that can't get copy paste right",
  "UseName": "somename",
  "Password": "SENSITIVE"_

The problemn does not occur with selection on a single line, nor with vertical (alt) selection.

Please do NOT fix THIS issue, but fix the real issue if you can (fix the copy paste BUG in visual studio)

**Comment by Nils-Berghs** [comment]
Apparently this is the same as #67

**Comment by madskristensen** [comment]
This is fixed in the latest version (currently uploading to Marketplace)
