### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [madskristensen/Tweakster#82]
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by madskristensen** [comment]
There is, but it's a separate extension called "Tweaks 2022"

**Comment by Gakk** [comment]
@madskristensen When searching for "Tweaks 2022" in the marketplace I get no results:

![image](https://user-images.githubusercontent.com/5013909/160106074-af2c6929-2d95-4f6c-ad4e-8c3952067601.png)

Should it be listed in the marketplace?

**Comment by Gakk** [comment]
Found it now. Even if it is not listed when searching in the marketplace, it shows as _[Preview]_ when searching in Visual Studio 😀👍

Link for others looking for the 2022-extension:
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.Tweaks2022
