### ISSUE TITLE
Can you make the Tweaks options searchable like all other options?

### ISSUE THREAD

**Issue by szalapski** [madskristensen/Tweakster#85]
Thanks for the great extension.  Can you make the Tweaks options searchable?  Example:  When I go to Tools -> Options and use the "search options" filter for "save", I expect to see "Tweaks 2019" since it has an "Auto save" option, but it does not appear.  

![image](https://user-images.githubusercontent.com/2723505/127664986-ff6da6e4-c1bd-4dc4-923c-8bec481bdc3f.png)
![image](https://user-images.githubusercontent.com/2723505/127665071-98daa789-7ca6-4677-a8c1-5bb2902f244d.png)

**Comment by szalapski** [comment]
(from https://stackoverflow.com/questions/68592238)

**Comment by madskristensen** [comment]
@gundermanc shouldn't DialogPage properties be searchable by default? How do it make them searchable?

**Comment by gundermanc** [comment]
>shouldn't DialogPage properties be searchable by default? 

No, unfortunately from Tools > Options infrastructure perspective, pages are just a UI element, and we don't know any of the content within.

To make your page show up in search under a different term, you can add additional keywords to your ProvideOptionPageAttribute on your VS package.

**Comment by richardlawley** [comment]
I don't think that https://github.com/madskristensen/Tweakster/commit/23f8f3e9f8154f2fa275ac6245bfc82ea5eebd80 actually fixed this - I tried searching for some of the terms in the commit without any results pointing at Environment > Tweaks:

![image](https://user-images.githubusercontent.com/1608083/139648490-8a0cec78-0b0d-4906-92ac-541e9703913f.png)

Tested under VS 2019 and 2022, both at latest versions.  Tested with the search box in the Options dialog, and in the Search everything (Ctrl-Q) box.
