### ISSUE TITLE
publish on open-vsx?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [madskristensen/Tweakster#91]
Hi!
I just thought to ask that do u have any plans to publish ur extension on open-vsx??
See this for more details: [MadsKristensen.Tweaks]
Thanks!

[MadsKristensen.Tweaks]: https://open-vsx.org/vscode/item?itemName=MadsKristensen.Tweaks

**Comment by madskristensen** [comment]
No, because that's for VSCode extensions. I publish mine to both the offiial Visual Studio Marketplace and to the [Open VSIX Gallery](https://www.vsixgallery.com/extension/0c8bd9fa-77d5-4563-ab57-9e01608c3d05)

**Comment by yashpalgoyal1304** [comment]
> No, because that's for VSCode extensions

ohww, ohkay, got it.
